version: "3"

services:
  node:
    image: node:19.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    volumes:
      - .:/home/node

  npm:
    extends: node
    entrypoint: npm

  npx:
    extends: node
    entrypoint: npx

  sh:
    extends: node
    entrypoint: sh
